CREATE TABLE orders (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    order_number VARCHAR(50) NOT NULL UNIQUE,
    user_id VARCHAR(36) NULL,
    customer_name VARCHAR(100) NOT NULL,
    customer_phone VARCHAR(20) NOT NULL,
    customer_email VARCHAR(100) NULL,
    subtotal DECIMAL(10, 2) NOT NULL,
    delivery_charge_text VARCHAR(255) NULL,
    grand_total DECIMAL(10, 2) NOT NULL,
    address_full_name VARCHAR(100) NULL,
    address_phone VARCHAR(20) NULL,
    address_line VARCHAR(255) NULL,
    address_area VARCHAR(100) NULL,
    address_city VARCHAR(50) NULL,
    address_state VARCHAR(50) NULL,
    address_pincode VARCHAR(20) NULL,
    address_landmark VARCHAR(100) NULL,
    preferred_delivery_date VARCHAR(50) NULL,
    preferred_delivery_time VARCHAR(100) NULL,
    payment_method VARCHAR(50) NOT NULL,
    order_status VARCHAR(50) NOT NULL,
    payment_status VARCHAR(50) NOT NULL,
    kitchen_notes TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE order_items (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    order_id VARCHAR(36) NOT NULL,
    product_id VARCHAR(50) NOT NULL,
    product_name VARCHAR(150) NOT NULL,
    product_image VARCHAR(500) NULL,
    category VARCHAR(100) NULL,
    weight_option VARCHAR(50) NULL,
    unit_price DECIMAL(10, 2) NOT NULL,
    quantity INT NOT NULL,
    subtotal DECIMAL(10, 2) NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE custom_cake_requests (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    user_id VARCHAR(36) NULL,
    customer_name VARCHAR(100) NULL,
    customer_phone VARCHAR(20) NULL,
    customer_email VARCHAR(100) NULL,
    cake_type VARCHAR(100) NOT NULL,
    flavor VARCHAR(100) NOT NULL,
    weight VARCHAR(50) NOT NULL,
    dietary_preference VARCHAR(50) NOT NULL,
    custom_message VARCHAR(255) NULL,
    special_instructions TEXT NULL,
    reference_image_url VARCHAR(500) NULL,
    reference_image_name VARCHAR(255) NULL,
    reference_image_size BIGINT NULL,
    preferred_delivery_date VARCHAR(50) NULL,
    preferred_delivery_time VARCHAR(100) NULL,
    status VARCHAR(50) NOT NULL,
    estimated_price DECIMAL(10, 2) NULL,
    confirmed_price DECIMAL(10, 2) NULL,
    feasibility_decision VARCHAR(50) NULL,
    bakery_notes TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_custom_cake_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
