CREATE TABLE products (
    id VARCHAR(50) NOT NULL PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    category VARCHAR(100) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    original_price DECIMAL(10, 2) NULL,
    description TEXT NOT NULL,
    short_description VARCHAR(500) NOT NULL,
    image VARCHAR(500) NOT NULL,
    gallery TEXT NULL,
    is_eggless BOOLEAN DEFAULT TRUE NOT NULL,
    is_available BOOLEAN DEFAULT TRUE NOT NULL,
    is_bestseller BOOLEAN DEFAULT FALSE NOT NULL,
    is_featured BOOLEAN DEFAULT FALSE NOT NULL,
    shelf_life VARCHAR(100) NULL,
    allergens TEXT NULL,
    ingredients TEXT NULL,
    weight_options TEXT NULL,
    min_lead_time_hours INT DEFAULT 24 NOT NULL,
    rating DOUBLE DEFAULT 5.0 NOT NULL,
    review_count INT DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP NULL,
    INDEX idx_products_category (category),
    INDEX idx_products_available (is_available),
    INDEX idx_products_deleted (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Seed authentic initial bakery catalogue
INSERT INTO products (id, name, category, price, original_price, description, short_description, image, gallery, is_eggless, is_available, is_bestseller, is_featured, shelf_life, allergens, ingredients, weight_options, min_lead_time_hours, rating, review_count)
VALUES
('prod-1', 'Traditional Rich Plum & Dry Fruit Cake', 'Cakes', 650.00, 750.00,
 'Our signature 100% eggless rich plum cake loaded with soaked candied cherries, plump raisins, roasted cashews, and aromatic festive spices. Baked slowly for deep, traditional homemade flavor.',
 'Classic eggless plum cake packed with soaked fruits and roasted nuts.',
 '/images/Product_1.jpeg', '["/images/Product_1.jpeg", "/images/Product_11.jpeg"]',
 TRUE, TRUE, TRUE, TRUE, '7–10 days in an airtight container',
 '["Tree Nuts (Cashews, Almonds)", "Gluten (Wheat)"]',
 '["Refined Wheat Flour", "Brown Sugar", "Butter", "Soaked Cherries", "Cashews", "Raisins", "Nutmeg", "Cinnamon"]',
 '["500g", "1kg", "1.5kg"]', 24, 4.9, 48),

('prod-2', 'Custom Chocolate Marbled Birthday Cake', 'Customized Cakes', 850.00, NULL,
 'Handcrafted eggless chocolate cake with an intricate spiderweb chocolate-vanilla ganache glaze. Includes a personalized festive celebration plaque.',
 'Custom birthday cake with signature marbled glaze and custom topper.',
 '/images/Product_2.jpeg', '["/images/Product_2.jpeg", "/images/Product_6.jpeg"]',
 TRUE, TRUE, TRUE, TRUE, '3–4 days refrigerated',
 '["Dairy (Milk, Butter)", "Gluten (Wheat)", "Soy Lecithin"]',
 '["Dutch Cocoa", "Flour", "Condensed Milk", "Butter", "Dark Chocolate Ganache", "Vanilla Extract"]',
 '["1kg", "1.5kg", "2kg"]', 24, 5.0, 62),

('prod-3', 'Royal Red Rosette Celebration Cake', 'Cakes', 950.00, 1100.00,
 'A stunning showstopper cake layered with velvety whipped cream and crowned with handcrafted fresh red rose buttercream swirls and edible sugar pearls.',
 'Velvety cream cake adorned with vibrant red rosette piping.',
 '/images/Product_3.jpeg', '["/images/Product_3.jpeg", "/images/Product_10.jpeg"]',
 TRUE, TRUE, FALSE, TRUE, '2–3 days refrigerated',
 '["Dairy (Cream, Butter)", "Gluten (Wheat)"]',
 '["Wheat Flour", "Fresh Cream", "Sugar", "Butter", "Natural Vanilla", "Edible Food Color"]',
 '["1kg", "1.5kg", "2kg"]', 24, 4.8, 35),

('prod-4', 'Artisanal Truffle & Vanilla Swirl Cake', 'Cakes', 780.00, NULL,
 'Rich layers of dark chocolate sponge soaked in sugar syrup, filled with rich chocolate mousse and finished with delicate vanilla-cocoa radial swirl icing.',
 'Dark chocolate sponge layered with creamy vanilla-cocoa swirl frosting.',
 '/images/Product_4.jpeg', '["/images/Product_4.jpeg"]',
 TRUE, TRUE, FALSE, FALSE, '3 days refrigerated',
 '["Dairy (Milk)", "Gluten (Wheat)"]',
 '["Dark Chocolate", "Dairy Cream", "Flour", "Cocoa Powder", "Sugar"]',
 '["500g", "1kg"]', 12, 4.7, 29),

('prod-5', 'Golden Buttercream Drip Celebration Cake', 'Cakes', 890.00, NULL,
 'Soft vanilla sponge with rich whipped caramel cream filling, decadent dark chocolate ganache drip, and handcrafted floral rosettes.',
 'Vanilla-caramel sponge with chocolate drip and rosette decor.',
 '/images/Product_5.jpeg', '["/images/Product_5.jpeg"]',
 TRUE, TRUE, FALSE, FALSE, '3 days refrigerated',
 '["Dairy", "Gluten"]',
 '["Flour", "Butter", "Cream", "Caramel Syrup", "Chocolate Drip"]',
 '["1kg", "1.5kg"]', 24, 4.8, 19),

('prod-6', '"Maa" Special Celebration Marble Cake', 'Customized Cakes', 900.00, NULL,
 'Special occasion celebration cake designed with chocolate marbling, fresh cream rosettes, sparkling silver pearls, and handcrafted chocolate plaque.',
 'Custom celebration cake featuring artisan marbled design and personalized plaque.',
 '/images/Product_6.jpeg', '["/images/Product_6.jpeg", "/images/Product_2.jpeg"]',
 TRUE, TRUE, TRUE, TRUE, '3–4 days refrigerated',
 '["Dairy", "Gluten", "Soy"]',
 '["Cocoa", "Cream", "Wheat Flour", "Sugar", "Silver Dragees", "Glaze"]',
 '["1kg", "1.5kg", "2kg"]', 24, 5.0, 54),

('prod-7', 'Classic Fresh Strawberry Cream Gateau', 'Cakes', 820.00, NULL,
 'Light sponge cake layered with sweet strawberry fruit compote, whipped vanilla cream, and chocolate lace decoration.',
 'Fruity strawberry gateau layered with silky whipped dairy cream.',
 '/images/Product_7.jpeg', '["/images/Product_7.jpeg"]',
 TRUE, TRUE, FALSE, FALSE, '2 days refrigerated',
 '["Dairy", "Gluten"]',
 '["Strawberry Compote", "Dairy Cream", "Flour", "Sugar", "Vanilla"]',
 '["500g", "1kg"]', 12, 4.7, 22),

('prod-8', 'Signature Caramel & Cocoa Ripple Pastry', 'Pastries', 150.00, NULL,
 'Single-serve layered eggless pastry with dark cocoa sponge, silky caramel mousse, and chocolate shavings.',
 'Individual chocolate caramel pastry slice with delicate ganache drip.',
 '/images/Product_8.jpeg', '["/images/Product_8.jpeg"]',
 TRUE, TRUE, TRUE, FALSE, '2 days refrigerated',
 '["Dairy", "Gluten"]',
 '["Cocoa", "Caramel", "Wheat Flour", "Fresh Cream"]',
 '["Single Slice", "Box of 2", "Box of 4"]', 6, 4.9, 41),

('prod-9', 'Velvet Strawberry Fantasy Pastry', 'Pastries', 160.00, NULL,
 'A delicate single-portion eggless pastry layered with crushed strawberries, vanilla creme, and glazed with white chocolate curls.',
 'Fresh strawberry and vanilla layered pastry slice.',
 '/images/Product_9.jpeg', '["/images/Product_9.jpeg"]',
 TRUE, TRUE, FALSE, FALSE, '2 days refrigerated',
 '["Dairy", "Gluten"]',
 '["Strawberries", "White Chocolate", "Cream", "Flour"]',
 '["Single Slice", "Box of 2"]', 6, 4.6, 18),

('prod-10', '"Happy Anniversary" Grand Rosette Drip Cake', 'Customized Cakes', 1350.00, 1500.00,
 'Grand double-flavor celebration cake. Half covered in red rosette piping with silver pearls, and half finished in dark chocolate crumble with golden caramel drip and acrylic anniversary topper.',
 'Stunning half-and-half anniversary cake with dual textures and toppers.',
 '/images/Product_10.jpeg', '["/images/Product_10.jpeg", "/images/Product_12.jpeg"]',
 TRUE, TRUE, TRUE, TRUE, '3 days refrigerated',
 '["Dairy", "Gluten", "Soy"]',
 '["Dutch Cocoa", "Strawberry Frosting", "Fresh Cream", "Wheat Flour", "Caramel Drip", "Sugar Pearls"]',
 '["1.5kg", "2kg", "3kg"]', 48, 5.0, 76),

('prod-11', 'Homemade Dark Chocolate Walnut Brownie (Box of 4)', 'Pastries', 340.00, NULL,
 'Dense, fudgy eggless chocolate brownies studded with toasted crunchy walnuts and melted dark chocolate chunks.',
 'Fudgy eggless chocolate brownies loaded with toasted walnuts.',
 '/images/Product_11.jpeg', '["/images/Product_11.jpeg"]',
 TRUE, TRUE, TRUE, FALSE, '5 days in an airtight container',
 '["Tree Nuts (Walnuts)", "Dairy", "Gluten"]',
 '["Dark Chocolate 55%", "Butter", "Walnuts", "Flour", "Brown Sugar"]',
 '["Box of 4", "Box of 8"]', 12, 4.9, 52),

('prod-12', 'Multi-Tier Royal Anniversary & Wedding Cake', 'Customized Cakes', 2400.00, NULL,
 'Custom 2-tier or 3-tier celebration masterpiece tailored to your theme, flavors, floral arrangements, and personalized messages.',
 'Multi-tier tiered celebration cake handcrafted for weddings and milestones.',
 '/images/Product_12.jpeg', '["/images/Product_12.jpeg", "/images/Product_10.jpeg"]',
 TRUE, TRUE, FALSE, TRUE, '3 days refrigerated',
 '["Dairy", "Gluten", "Tree Nuts (Optional)"]',
 '["Custom Flavors", "Fresh Whipped Cream", "Buttercream", "Edible Accents"]',
 '["2kg", "3kg", "5kg"]', 48, 5.0, 38),

('prod-13', 'Decadent Dark Chocolate Truffle Gateau', 'Cakes', 880.00, NULL,
 'Pure chocolate lover indulgence. Three layers of moist chocolate sponge filled and frosted with 60% dark chocolate truffle ganache.',
 'Triple-layer chocolate cake loaded with rich dark truffle ganache.',
 '/images/Product_13.jpeg', '["/images/Product_13.jpeg"]',
 TRUE, TRUE, TRUE, FALSE, '4 days refrigerated',
 '["Dairy", "Gluten", "Soy"]',
 '["Dark Chocolate Ganache", "Cocoa Sponge", "Butter", "Cream"]',
 '["500g", "1kg", "1.5kg"]', 12, 4.9, 67),

('prod-14', 'Handcrafted Butter Cookies & Biscuits (Pack of 12)', 'Cookies', 260.00, NULL,
 'Melt-in-your-mouth artisanal eggless butter cookies baked to golden perfection with real dairy butter and hints of cardamom.',
 'Crisp, crumbly homemade butter cookies baked fresh daily.',
 '/images/Product_14.jpeg', '["/images/Product_14.jpeg"]',
 TRUE, TRUE, FALSE, FALSE, '15 days in an airtight jar',
 '["Dairy (Butter)", "Gluten (Wheat)"]',
 '["Pure Dairy Butter", "Flour", "Icing Sugar", "Cardamom", "Vanilla"]',
 '["Pack of 12 (250g)", "Pack of 24 (500g)"]', 12, 4.8, 44),

('prod-15', 'Artisanal Sourdough & Herb Bread Loaf', 'Breads', 190.00, NULL,
 'Slow-fermented artisan homemade bread loaf infused with dried oregano, thyme, garlic, and extra virgin olive oil with a crisp crust.',
 'Slow-fermented crusty artisan loaf with rosemary and garlic.',
 '/images/Product_15.jpeg', '["/images/Product_15.jpeg"]',
 TRUE, TRUE, FALSE, FALSE, '3–4 days room temperature',
 '["Gluten (Wheat)"]',
 '["Stone-ground Wheat Flour", "Water", "Sea Salt", "Natural Sourdough Starter", "Herbs"]',
 '["400g Loaf"]', 24, 4.7, 26),

('prod-16', 'Assorted Floral Buttercream Cupcakes (Box of 6)', 'Cupcakes', 450.00, NULL,
 'Box of 6 moist eggless cupcakes in vanilla, red velvet, and chocolate topped with handcrafted piped floral rosettes in vibrant pastels.',
 'Box of 6 assorted moist cupcakes with delicate buttercream flowers.',
 '/images/Product_16.jpeg', '["/images/Product_16.jpeg", "/images/Product_17.jpeg"]',
 TRUE, TRUE, TRUE, TRUE, '3 days refrigerated',
 '["Dairy", "Gluten"]',
 '["Wheat Flour", "Buttercream", "Sugar", "Natural Flavors"]',
 '["Box of 6", "Box of 12"]', 12, 4.9, 50),

('prod-17', 'Rich Chocolate Lava Cupcakes (Box of 4)', 'Cupcakes', 320.00, NULL,
 'Decadent eggless chocolate cupcakes with a warm, gooey molten chocolate ganache core. Warm for 10 seconds before serving!',
 'Decadent cupcakes with a gooey molten chocolate ganache center.',
 '/images/Product_17.jpeg', '["/images/Product_17.jpeg"]',
 TRUE, TRUE, FALSE, FALSE, '3 days refrigerated',
 '["Dairy", "Gluten", "Soy"]',
 '["Dark Chocolate", "Butter", "Flour", "Brown Sugar"]',
 '["Box of 4", "Box of 8"]', 12, 4.9, 37),

('prod-18', 'Custom Theme Tiered Party Cake', 'Customized Cakes', 1800.00, NULL,
 'Bespoke celebration cake custom sculpted and themed to your party style. Choose your flavors, cake toppers, whipped cream shades, and custom lettering.',
 'Tailored theme cake designed for birthdays, milestones, and parties.',
 '/images/Product_18.jpeg', '["/images/Product_18.jpeg", "/images/Product_10.jpeg"]',
 TRUE, FALSE, FALSE, FALSE, '3 days refrigerated',
 '["Dairy", "Gluten"]',
 '["Flour", "Butter", "Cream", "Chocolate Ganache", "Custom Elements"]',
 '["2kg", "3kg"]', 48, 4.9, 28);
